[env:esp32-2432s024n]
platform = espressif32
board = esp32-2432s024n
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyUSB*
monitor_port = /dev/ttyUSB*
lib_ldf_mode = chain+

lib_deps =
  h2zero/NimBLE-Arduino@^1.4.2
  fastled/FastLED@^3.7.0
  bodmer/TFT_eSPI@^2.5.43

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DUSER_SETUP_LOADED
  -include include/User_Setup.h
  -DMY_PROJECT_VERSION=13
  -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/FS/src
  -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/SPIFFS/src
